# *********************************
# * Parameters for metqc pipeline *
# *********************************

# List of files
list_files: "/bulk/IMCshared_bulk/sycuro_shared_projects/IMPACTT_benchmarking/IMPACTT_sample_handling/shotgun/2022_09_09/analysis/list_files.txt"

# Input directory Path to raw sequences
input_dir: "/bulk/IMCshared_bulk/sycuro_shared_projects/IMPACTT_benchmarking/IMPACTT_sample_handling/shotgun/2022_09_09/data/"

# Output directory path for output files.
output_dir: "output"

# Suffix for forward reads.
forward_read_suffix: "_1.fastq.gz"

# Suffix for reverse reads.
reverse_read_suffix: "_2.fastq.gz"

# Run fastqc and multiqc only
qc_only: FALSE

### Cutadapt parameters

# The number of cpu cores to use for cutadapt
num_cpus: 7

# Choose whether to run cutadapt
run_cutadapt: TRUE

# Adapters for cutadapt
fwd_adapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
rev_adapter: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

### Prinseq parameters
trimleft: 0
trimright: 0
trim_qual_left: 30
trim_qual_right: 30
trim_qual_window: 10
trim_qual_step : 2
trim_qual_type: "mean"
trim_qual_rule: "lt"
lc_method: "dust"
lc_threshold: 7

# Minimum length for reads
minlength: 60

# Maximum number of N bases allowed
maxn: 15

### BMtagger Parameters

# Choose whether to run bmtagger
run_bmtagger: TRUE

# Index for bmfilter (part of bmtagger), bitmask file
bmfilter_ref: "/bulk/IMCshared_bulk/shared/dbs/bmtaggerDB/hg19_rRNA_mito_Hsapiens_rna/hg19_rRNA_mito_Hsapiens_rna_reference.bitmask"

# Index for srprism (part of bmtagger)
srprism_ref: "/bulk/IMCshared_bulk/shared//dbs/bmtaggerDB/hg19_rRNA_mito_Hsapiens_rna/hg19_rRNA_mito_Hsapiens_rna_reference.srprism"

### BBMap parameters
# Choose whether to run bbmap
run_bbmap: FALSE

# Path and name of reference fasta for bbmap
bbmap_ref: "/home/aschick/refs/hs37.fa"

